# Generated by Django 5.0.6 on 2025-09-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentuser',
            managers=[
            ],
        ),
    ]
