# Generated by Django 5.0.6 on 2025-09-03 16:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('financier', 'Financier')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='FinancierUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financier_id', models.CharField(help_text='Financier ID', max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name (if applicable)', max_length=100, null=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount invested in the platform', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Interest rate earned (2% default)', max_digits=4)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account for interest payments', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financier Profile',
                'verbose_name_plural': 'Financier Profiles',
                'ordering': ['-user__created_at'],
            },
        ),
    ]
