# Generated by Django 5.0.6 on 2025-09-02 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Loan amount in INR (500-5000)', validators=[django.core.validators.MinValueValidator(500, message='Minimum loan amount is 500 INR'), django.core.validators.MaxValueValidator(5000, message='Maximum loan amount is 5000 INR')])),
                ('reason', models.TextField(help_text='Reason for loan application')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repayment_due_date', models.DateField(help_text='Due date for loan repayment')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Annual interest rate (%)', max_digits=4)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
