# Generated by Django 5.0.6 on 2025-09-03 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.IntegerField(help_text='Loan amount in INR (500-100,000)', validators=[django.core.validators.MinValueValidator(500, message='Minimum loan amount is 500 INR'), django.core.validators.MaxValueValidator(100000, message='Maximum loan amount is 100,000 INR')]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Monthly simple interest rate (%) (used for display; calculation fixed at 10%)', max_digits=4),
        ),
    ]
