# Generated by Django 5.0.6 on 2025-09-02 17:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')])),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(default='Manual Entry', help_text='Method of payment (Manual Entry, UPI, Bank Transfer, etc.)', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Repayment',
                'verbose_name_plural': 'Repayments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
