# Generated by Django 5.0.6 on 2025-10-07 05:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayments', '0001_initial'),
        ('users', '0003_studentuser_user_type_financieruser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number (masked)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for transfer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Payment gateway response data', null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was processed', null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_repayments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID used for payment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_method',
            field=models.CharField(choices=[('Manual Entry', 'Manual Entry'), ('UPI', 'UPI (PhonePe, Google Pay, Paytm, BHIM)'), ('Bank Transfer', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('Net Banking', 'Net Banking'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Wallet', 'Digital Wallet'), ('Cash', 'Cash Payment'), ('Cheque', 'Cheque'), ('DD', 'Demand Draft'), ('Razorpay', 'Razorpay Gateway'), ('PayPal', 'PayPal'), ('Stripe', 'Stripe')], default='Manual Entry', help_text='Method of payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(100.0, message='Minimum withdrawal amount is 100 INR')])),
                ('withdrawal_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI Transfer'), ('Cheque', 'Cheque'), ('DD', 'Demand Draft'), ('Wire Transfer', 'International Wire Transfer')], default='Bank Transfer', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank transaction ID', max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the withdrawal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='users.financieruser')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
