# Generated by Django 5.0.6 on 2025-10-07 09:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_amount_and_more'),
        ('repayments', '0002_repayment_account_number_repayment_bank_name_and_more'),
        ('users', '0003_studentuser_user_type_financieruser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000.0, message='Minimum investment amount is 1,000 INR')])),
                ('expected_return_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Expected annual return rate (%)', max_digits=4)),
                ('investment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI Transfer'), ('Cheque', 'Cheque'), ('DD', 'Demand Draft'), ('Wire Transfer', 'International Wire Transfer'), ('Online Payment', 'Online Payment Gateway')], default='Bank Transfer', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Defaulted', 'Defaulted')], default='Pending', max_length=20)),
                ('investment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when investment was made')),
                ('maturity_date', models.DateTimeField(help_text='Expected maturity date for the investment')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID for the investment payment', max_length=100, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=200, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Payment gateway response data', null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the investment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='users.financieruser')),
                ('loan', models.ForeignKey(help_text='Loan application being invested in', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='loans.loanapplication')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this investment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-created_at'],
                'unique_together': {('financier', 'loan')},
            },
        ),
    ]
